name: Preview (build)

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths-ignore:
      - 'docs/'
      - '.md'
      - 'tests/'
      - '!tests/.sh'
      - '!tests/apitests/'
      - '!tests/ci/'

permissions:
  contents: read
  pull-requests: write
  id-token: write
  actions: write

jobs:
  build-kube-dashboard:
    name: Build Kube Dashboard
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
        with:
          repository: kubernetes/dashboard
      # - name: Build Kube Dashboard
      #   run: |
      #     echo "Building Kube Dashboard"
      #     echo "Kube Dashboard is built"
      #     # make docker-build-head
      - name: Generate UUID image name
        id: uuid
        run: echo "UUID_CORE=$(uuidgen)" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.uffizzi.com/${{ env.UUID_CORE }}
          tags: type=raw,value=60d
      - name: Build and Push Image to Uffizzi Ephemeral Registry
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./make/photon/core/Dockerfile
          context: .
          build-args: |
            harbor_base_image_version=dev
            harbor_base_namespace=goharbor
            npm_registry=https://registry.npmjs.org

  uffizzi-cluster-delete:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete Virtual Cluster
        uses: UffizziCloud/cluster-action@main
        with:
          action: delete
          cluster-name: pr-${{ github.event.pull_request.number }}
      - name: Upload PR Event as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: preview-spec
          path: ${{ github.event_path }}
          retention-days: 2